### ISSUE TITLE
Inconsistent replacement of NULL_KEY with ""

### ISSUE THREAD

**Issue by tapple** [Sei-Lisa/LSL-PyOptimizer#11]
the optimizer breaks this script:
```
integer driverListener;

startDriverAndOwnerListener(key driver)
{
    llListenRemove(driverListener);
    if (driver != NULL_KEY)
    {
        driverListener = llListen(483, "", driver, "");
    }
}

default
{
    state_entry()
    {
        startDriverAndOwnerListener(NULL_KEY);
    }
}
```

output:
```
integer driverListener;

startDriverAndOwnerListener(key driver)
{
    llListenRemove(driverListener);
    if (!(driver == "00000000-0000-0000-0000-000000000000"))
    {
        driverListener = llListen(483, "", driver, "");
    }
}

default
{
    state_entry()
    {
        startDriverAndOwnerListener("");
    }
}
```

NULL_KEY is replaced with "" in state_entry, but not in the if condition

**Comment by tapple** [comment]
I'll work around this by using "" in the source script. Didn't know that worked in llListen

**Comment by Sei-Lisa** [comment]
Thanks for the report. Most library functions behave the same when passing `""` as when passing `NULL_KEY` for key type arguments. The only known exception is `llMessageLinked`. The problem was that UDFs were being optimized by mistake as if they were library functions. I've pushed a fix.

In this case, you could also use:

```lsl
    if (driver)
    {
        driverListener = llListen(483, "", driver, "");
    }
```

which checks that the key is both valid and non-NULL, pretty much like most internal LSL functions do.
