### ISSUE TITLE
Jump statements with default returns delete the required return value

### ISSUE THREAD

**Issue by Tonaie** [Sei-Lisa/LSL-PyOptimizer#14]
This is a little of a special case because jump statements are rarely used but take this function for an example:

<pre>
list out(){
    integer n = 3;
    @continue;
    llOwnerSay((string)n);
    --n;
    if( !n )
        return [];
    jump continue;
    return [];    
}
</pre>

After optimizing:

<pre>
list _()
{
    integer loc_n = 3;
    @J_autoGen00001;
    llOwnerSay((string)loc_n);
    --loc_n;
    if (!loc_n)
        return [];
    jump J_autoGen00001;
    // Note that return []; was removed here
}
</pre>

Even though the ```return [];``` at the end of the original function is never reached because of the jump statement, LSL requires it in order to compile.

**Comment by Sei-Lisa** [comment]
Thanks a lot, and that was a nice test case! I've added it to the test suite, please let me know if that's a problem for you.

**Comment by Sei-Lisa** [comment]
Oops, I pressed the send button too soon.

There were several problems here:

* The return value of `RETURN` statements was being deleted from the statement; when the constant folding module saw a `RETURN` without parameters as a last statement, it thought it was OK to remove it (it would, if that was valid, so that part was actually working correctly).
* The dead code removal was too greedy, removing any dead code regardless of whether it's syntactically necessary, as you noted. Unfortunately, Linden Lab's code path analyser is not good enough to detect that the rest of the function won't ever be executed and ignore it.

The fix is already committed and applied to the online version.

A test case had to be disabled because this fix brought back a RETURN statement in it.
