### ISSUE TITLE
--postarg is ignored

### ISSUE THREAD

**Issue by Blues-Today** [Sei-Lisa/LSL-PyOptimizer#18]
patch attached
[0001-Add-missing-code-to-support-postarg.patch.txt](https://github.com/Sei-Lisa/LSL-PyOptimizer/files/8923535/0001-Add-missing-code-to-support-postarg.patch.txt)

**Comment by Sei-Lisa** [comment]
Thanks for the report! Evidently some preprocessor options are not well tested.

Funnily, the internal preprocessor branch already included that fix. Apparently I failed to notice that it also applies to the master branch.

I've added a regression test as well, which required a new option --preproc-show-cmdline in order to allow the test to see the arguments (and might be useful to debug preprocessor issues).

Thanks again.
