### ISSUE TITLE
NAK causes Firestorm script compiler to error

### ISSUE THREAD

**Issue by Blues-Today** [Sei-Lisa/LSL-PyOptimizer#30]
When attempting to use the NAK constant to detect uncached notecards with llGetNotecardLineSync () in a script, LSL-PO replaces the NAK constant with a string consisting of "\n^U\n", (i.e., %0A%15%0A).

The Firestorm compiler then produces the following error:

error: generic lexer error: invalid character '\025' in input stream

when it encounters the CTRL-U.

**Comment by PeterStindberg** [comment]
See https://jira.firestormviewer.org/browse/FIRE-33703

**Comment by Blues-Today** [comment]
I hacked lslopt/lsloutput.py to make it output NAK instead of the expanded string, which the compiler is happy with.  There's probably a better way to do this, but I don't grok the internals of LSL-PO well enough to suggest one :)

```
@@ -63,9 +63,13 @@ class outscript(object):
                          " spaces by the viewer when copy-pasting the code"
                          " (disable this warning by disabling the 'warntabs'"
                          " option).")
-            return (pfx + '"' + u2str(unicode(value), 'utf8')
+            quoted = '"'
+            if u'\x15' in value:
+                value = 'NAK'
+                quoted = ''
+            return (pfx + quoted + u2str(unicode(value), 'utf8')
                 .replace('\\','\\\\').replace('"','\\"').replace('\n','\\n')
-                + '"' + sfx)
+                + quoted + sfx)
         if tvalue == int:
             if value < 0 and not self.globalmode and self.optsigns:
                 #return '0x%X' % (value + 4294967296)
```

**Comment by Kristyku** [comment]
This all comes down to the way the optimizer expands all constants in order to be able to constant fold them later.

It works great for binary flags or numeric values, or null key as a string and so on. But there are a few constants that ideally should be kept as constants as they effectively are error codes - NAK, EOF and possibly some others and I can't really think of a case where you'd want those to be expanded/constant folded into anything.

I feel like the optimizer should have some sort of exclusion list to know which constants to leave untouched, and maybe even have an option to turn it on/off.

**Comment by PeterStindberg** [comment]
> I hacked lslopt/lsloutput.py to make it output NAK instead of the expanded string, which the compiler is happy with. There's probably a better way to do this, but I don't grok the internals of LSL-PO well enough to suggest one :)
> 

Tried this, but got errors downstream.

Traceback (most recent call last):
  File "/Users/xxx/Scripts/GitHub/LSL-PyOptimizer/main.py", line 782, in <module>
    ret = main(sys.argv)
  File "/Users/xxx/Scripts/GitHub/LSL-PyOptimizer/main.py", line 745, in main
    script = script_header + script_timestamp + outs.output(ts, options)
  File "/Users/xxx/Scripts/GitHub/LSL-PyOptimizer/lslopt/lsloutput.py", line 560, in output
    ret += self.OutCode(node)
  File "/Users/xxx/Scripts/GitHub/LSL-PyOptimizer/lslopt/lsloutput.py", line 485, in OutCode
    ret += ' = ' + self.OutExpr(child[0].orig)
  File "/Users/xxx/Scripts/GitHub/LSL-PyOptimizer/lslopt/lsloutput.py", line 315, in OutExpr
    return self.Value2LSL(expr.value)
  File "/Users/xxx/Scripts/GitHub/LSL-PyOptimizer/lslopt/lsloutput.py", line 181, in Value2LSL
    assert False, u'Value of unknown type in Value2LSL: ' + repr(value)
AssertionError: Value of unknown type in Value2LSL: u'New Script'

**Comment by Sei-Lisa** [comment]
I'm on the fence on this one. Am I right that this is only a problem in Firestorm when the preprocessor is enabled? And if so, is there a reason not to be using PyOpt built-in preprocessor support instead?

Edit: By the way, the "ugly hack" should at least use the whole expansion of the `NAK` constant, which is `u'\n\x15\n'`.

**Comment by Kristyku** [comment]
The case I use it is: my script in SL is just #include <actual script> and in order for that to work, FS Preprocessor has to be enabled, even though it includes already preprocessed file.

If you disable FS Preprocessor and copy-pate manually it works fine. but then you need to copy paste stuff by hand...

**Comment by Sei-Lisa** [comment]
Yes, that's a very reasonable use case, having done that myself. The simplest approach will probably be to treat the blacklisted string constants as variables with an unknown value, to prevent them from being expanded. I'll look into it.

**Comment by Blues-Today** [comment]
I'm in exactly the same boat as Krsity.  My in-world scripts consists of a single #include to pull in the output of LSL-PO which won't work if you turn off the FS preprocessor.  And I blame Peter for calling my workaround "ugly": it works, it saved me a month, and I got to learn stuff about the internals of your code :)

**Comment by PeterStindberg** [comment]
I don't use a single include, in fact so far I don't use any includes at all (I really should start), but I use a lot of conditional compile statements #ifdef / #ifndef. The FS proprocessor removes this "dead" code depending on the defines, and that code gets then processed by PyOp.

**Comment by Sei-Lisa** [comment]
@PeterStindberg 

> I don't use a single include, in fact so far I don't use any includes at all (I really should start), but I use a lot of conditional compile statements #ifdef / #ifndef. The FS proprocessor removes this "dead" code depending on the defines, and that code gets then processed by PyOp.

Off-topic for this issue report, but PyOp includes support for running a preprocessor, see http://seis.blacktulip-virtual.com/lsl-pyoptimizer/#using-the-program so that you don't need to run it every time through Firestorm to preprocess it.

**Comment by Sei-Lisa** [comment]
Okay, so I've added the `--blacklist` option to declare a blacklist, which defaults to: `NAK,JSON_*`, but it comes with some caveats.

- Most importantly, since a new symbol type has been introduced, it may and almost surely will cause regressions. The current test suite passes, but of course the blacklisted constants are barely tested or not at all.
- Currently, all JSON_* constants are blacklisted. This includes `JSON_APPEND`, which is actually an integer with a value of -1. It can be refined to exclude that one, but it's a bit uncomfortable to do so.
- The error messages produced by the blacklisted constants differ from what SL would report, and are not even consistent. For example, `++NAK;` would produce a syntax error in SL, but in the optimizer it produces "Name not defined within scope". There are about five places in that situation. On the other hand, `NAK++;` correctly produces a syntax error.
- There is no error or warning for duplicate blacklist entries (although they don't cause problems) or for non-existing constants.

**Comment by Blues-Today** [comment]
Confirmed working with no apparent issues.  Thank you!
