### ISSUE TITLE
Invalid signs after const folding with Optimize signs disabled.

### ISSUE THREAD

**Issue by Kristyku** [Sei-Lisa/LSL-PyOptimizer#31]
The following code:
```lsl
default
{
	link_message(integer p_val, integer notUsed1, string notUsed2, key notUsed3)
	{
		float pivot_x = 0.0;
		float pivot_y = -0.65;
		float theta = 0.01 * p_val;

		float x = pivot_x * llCos(theta) - pivot_y * llSin(theta);
		float y = pivot_x * llSin(theta) + pivot_y * llCos(theta);
		
		llOwnerSay("Pivot: " + (string)x + ", " + (string)y);
	}
}
```
Optimizes to:
```lsl
default
{
	link_message(integer p_val, integer notUsed1, string notUsed2, key notUsed3)
	{
		float theta = 0.01 * p_val;
		float x = --0.65 * llSin(theta);
		float y = -0.65 * llCos(theta);
		llOwnerSay("Pivot: " + (string)x + ", " + (string)y);
	}
}
```
`--0.65` is a syntax error
Using options: Constant folding, Dead code removal, but with Optimize signs disabled.

Because of pivot_x being 0, the formula collapses in to:
```
x = 0 - y * llSin(θ)
x = 0 - (-0.65 * sin(θ))
x = -(-0.65 * sin(θ))
```
but since the optimizer does not use parentheses, it becomes a `--` operator.

**Comment by Sei-Lisa** [comment]
Yes, it's broken, thanks for the report. There's special code to add spaces between minus signs if there are several in a row, but in this case the optimizer fails to realize that the constant `-0.65` starts with a minus sign, because in this case, that minus sign is not an AST node but embedded in the value.

The correct output according to the AST would be `x = -(-0.65) * llSin(theta)`, because the unary minus has less precedence than the product, which is one of the many LSL quirks. Nevertheless, it would be nice if the sign could be optimized out. I'll look into it.
