### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode character

### ISSUE THREAD

**Issue by Jomik** [Sei-Lisa/LSL-PyOptimizer#5]
I have the following `snippet.lsl` that causes the above error.

```lsl
integer menuChannel = 1;

showDialog(string user, string description, list buttons) {
    llDialog(user, description, buttons, menuChannel);
}

default {
    state_entry() {
        string pageString = " ";
        list options = [];
        showDialog(llGetOwner(), "Test", ["◀" + " Prev" + pageString, "▼" + " Back", "▶" + " Next" + pageString] + llList2List(options, page * 9, page * 9 + 8);
    }
}
```
I run `python ./optimizer/main.py -H -O addstrings,-extendedglobalexpr,optsigns,optfloats .\snippet.lsl -o .\snippet.lslo`

And here's a traceback with -y.
```
Traceback (most recent call last):
  File "./optimizer/main.py", line 661, in <module>
    ret = main(sys.argv)
  File "./optimizer/main.py", line 630, in main
    ReportError(script, e)
  File "./optimizer/main.py", line 36, in ReportError
    sys.stderr.write(script[fieldpos(script, '\n', e.lno):lastpos].decode('utf8') + u"\n")
  File "C:\Python27\lib\encodings\cp850.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_map)
UnicodeEncodeError: 'charmap' codec can't encode character u'\u25c0' in position 43: character maps to <undefined>
```

The line that causes the error is `showDialog(llGetOwner(), "Test", ["◀" + " Prev" + pageString, "▼" + " Back", "▶" + " Next" + pageString] + llList2List(options, page * 9, page * 9 + 8);`
More specifically, I'm missing a closing parenthesis.

I'm on a Windows 10 machine, if that matters 👍

**Comment by Sei-Lisa** [comment]
Thanks for the report! The problem here is that the console encoding does not support the Unicode characters that it is going to print when attempting to quote the line where the syntax error occurs.

It would be nice to be able to replace the characters with backslashes, so that the console can display something distinctive but it's going to be difficult to do that while reporting a sensible marker position, because the column count gets screwed up, since each character occupies at least 6 spaces. I'll see what can be done. Failing that, I'll use question marks as replacement.

**Comment by Sei-Lisa** [comment]
I've submitted a fix that I believe should be quite robust against any encoding problems at that spot; the marker and the column number both report the correct position now. If the terminal doesn't support the characters that are printed, the example above is now reported as:

```
        showDialog(llGetOwner(), "Test", ["\u25c0" + " Prev" + pageString, "\u25bc" + " Back", "\u25b6" + " Next" + pageString] + llList2List(options, page * 9, page * 9 + 8);
                                                                                                                                                       ^
(Line 11 char 137): ERROR: Name not defined within scope
```

The column number (137) is now in characters, rather than bytes.

Please see #6 for details, and please test if possible to verify it works in your system as well.

**Comment by Sei-Lisa** [comment]
> More specifically, I'm missing a closing parenthesis.

Just to clarify, in your snippet there's a missing identifier (`page`) before that, and that's the error being reported.

There are differences between the LSL compiler and the optimizer, in how errors are reported. The compiler first checks the syntax and builds the AST with a shift-reduce parser (bison), then runs a series of passes on the AST to resolve identifiers, assign variables, etc. Lingo aside, the visible consequence is that syntax errors are reported before everything else. If you haven't defined a variable, have type mismatches, miss parameters to functions, etc. but you have, say, an extra close brace at the end of the file, it reports the syntax error. Only after you fix the syntax error can it tell you about the other errors; sometimes it does so once per pass, resulting in the same error being reported multiple times.

By contrast, the optimizer uses a recursive-descendent parser that builds the AST and the symbol table in the same pass. There is a quick globals pass first, but that's very permissive about syntax errors and is only used to resolve forward references to globals in functions. As a result, errors are reported as soon as they appear in the code; in this case, it finds the missing identifier before the syntax error.

The position of the missing identifier was reported at the character following the identifier rather than at the identifier itself, due to an issue with having to resolve whether it's a function call, so it knows which symbol table to look it up in. #6 fixes that as well, by taking note of the position of the identifier and rewinding the error position as appropriate if the error is triggered.
