### ISSUE TITLE
Optimizer ignores implicit float casting

### ISSUE THREAD

**Issue by Welcius** [Sei-Lisa/LSL-PyOptimizer#8]
Assuming the input is x = 5, y = 2

The following function f returns 3:

`integer f (integer x, integer y) {
    return llCeil(x * 1.0 / y);
}`

Previous function gets optimized to a function q like this, which returns 2:

`integer q (integer x, integer y)
{
    return llCeil(x / y);
}`

Therefore I think that the optimizer should be able to handle this type of implicit float casting, if not we will get unexpected results due to the properties of integer division.

**Comment by Sei-Lisa** [comment]
Wow, yeah, that's not supposed to happen. Thanks for the report.

**Comment by Sei-Lisa** [comment]
This was an oversight in the optimization of -2, -1, 0, 1 and 2 (float or integer) multiplied by a non-constant. The addition was done correctly (e.g. x + 0.0 + y would produce a cast to float), and operating with constants produced the correct result, but I missed the case of multiplication by a non-constant.

Fixed in 1bdaff3, with corresponding test case. Thanks again!

**Comment by Welcius** [comment]
Thank you for your hard work!
